$ErrorActionPreference="Stop";Add-Type -AssemblyName System.Drawing
$root=Join-Path (Resolve-Path ".").Path "assets/runtime/ui/secondary_v2";$out=Join-Path $root "contact_sheet_batch2.png"
$items=@(
@("Task row","pages/daily/task_row.png"),@("Signin default","pages/daily/signin_day_default.png"),@("Signin today","pages/daily/signin_day_today.png"),@("Chest ready","pages/daily/activity_chest_ready.png"),@("Claimable","pages/daily/status_claimable.png"),@("Claimed","pages/daily/status_claimed.png"),
@("Benefit card","pages/commerce/benefit_card.png"),@("Reward blue","pages/commerce/reward_slot_blue.png"),@("Reward purple","pages/commerce/reward_slot_purple.png"),@("Chest closed","pages/commerce/first_chest_closed.png"),@("Chest open","pages/commerce/first_chest_open.png"),@("Reward altar","pages/commerce/first_reward_altar.png"),
@("Piggy empty","pages/commerce/piggy_empty.png"),@("Piggy filling","pages/commerce/piggy_filling.png"),@("Piggy full","pages/commerce/piggy_full.png"),@("Piggy owned","pages/commerce/piggy_owned.png"),@("Product slot","pages/shop/product_slot_default.png"),@("Unavailable","pages/shop/product_slot_unavailable.png"),
@("Coin bundle","pages/shop/icon_coin_bundle.png"),@("Crystal bundle","pages/shop/icon_crystal_bundle.png"),@("Star hammer","pages/shop/icon_star_hammer.png"),@("Fire conduit","pages/shop/icon_fire_conduit.png"),@("Steam furnace","pages/shop/icon_steam_furnace.png"),@("Clockwork","pages/shop/icon_clockwork.png"),
@("Prism","pages/shop/icon_prism.png"),@("Cannon","pages/shop/icon_cannon.png"),@("Imprint chest","pages/shop/icon_imprint_chest.png"),@("Crystal price","pages/shop/price_strip_crystal.png"),@("Money price","pages/shop/price_strip_money.png"),@("Quantity row","pages/shop/purchase_quantity_row.png")
)
$bmp=[System.Drawing.Bitmap]::new(1400,1160,[System.Drawing.Imaging.PixelFormat]::Format32bppArgb);$bmp.SetResolution(96,96);$g=[System.Drawing.Graphics]::FromImage($bmp);$g.SmoothingMode='AntiAlias';$g.Clear([System.Drawing.ColorTranslator]::FromHtml("#E7EDF5"))
$title=[System.Drawing.Font]::new("Arial",28,[System.Drawing.FontStyle]::Bold);$label=[System.Drawing.Font]::new("Arial",13);$dark=New-Object System.Drawing.SolidBrush ([System.Drawing.ColorTranslator]::FromHtml("#19334F"));$g.DrawString("Secondary UI V2 - Batch 2 runtime assets",$title,$dark,34,22)
for($i=0;$i-lt $items.Count;$i++){$col=$i%6;$row=[Math]::Floor($i/6);$x=30+$col*225;$y=85+$row*207;$white=New-Object System.Drawing.SolidBrush ([System.Drawing.Color]::White);$g.FillRectangle($white,$x,$y,205,185);$white.Dispose();$pen=New-Object System.Drawing.Pen ([System.Drawing.ColorTranslator]::FromHtml("#B7C6D8"),2);$g.DrawRectangle($pen,$x,$y,205,185);$pen.Dispose();$img=[System.Drawing.Image]::FromFile((Join-Path $root $items[$i][1]));$s=[Math]::Min(170.0/$img.Width,125.0/$img.Height);$dw=[int]($img.Width*$s);$dh=[int]($img.Height*$s);$g.DrawImage($img,$x+[int]((205-$dw)/2),$y+9+[int]((125-$dh)/2),$dw,$dh);$img.Dispose();$sf=New-Object System.Drawing.StringFormat;$sf.Alignment='Center';$sf.LineAlignment='Center';$g.DrawString($items[$i][0],$label,$dark,[System.Drawing.RectangleF]::new($x+5,$y+140,195,34),$sf);$sf.Dispose()}
$g.Dispose();$bmp.Save($out,[System.Drawing.Imaging.ImageFormat]::Png);$bmp.Dispose();$title.Dispose();$label.Dispose();$dark.Dispose();Write-Output $out
